### PR TITLE
Fix Changed default text color to #4f4f4f

### LINKED ISSUE #1949: Update default text color to #4f4f4f

### PR DESCRIPTION
**Pull request by shubhalgupta**

### CODE REVIEW

**Comment by shubhalgupta** [comment]
@juujisai please review!

**Comment by juujisai** [comment]
Hi. This task is planned for the v2.0.0 version, so it will have to wait. 

BTW, `text-#4f4f4f` this won't work. Try this instead `text-[#4f4f4f]`

**Comment by juujisai** [comment]
Please fix the issue with the `text` classes of this PR that I mentioned before

**Comment by shubhalgupta** [comment]
Alright. Will do the same.

**Comment by juujisai** [comment]
Closing duplicate https://github.com/mdbootstrap/TW-Elements/pull/2030

**Pull request closed without merging**
