### PR TITLE
Add 'includePadding' option

### PR DESCRIPTION
**Pull request by malroc**
Add 'includePadding' option (use container outerWidth/outerHeight instead of width/height)

### CODE REVIEW

**Comment by hatashiro** [comment]
Hello,

I'm very sorry for the late response.
It looks good, and can you add a document into the README file about the option please?

When you add the document and upload with a pull request again, I'll merge them all at once.

Thanks!

**Comment by febLey** [comment]
This is great, i've got the problem, that my container has a paddding, but the plugin only takes the .height(). This'll fix it.

**Comment by hatashiro** [comment]
I recently fixed up some commits and it makes the commit tree messed. I manually cherry-picked your patch.

I also added the description to README.md.

Thanks!

**Comment by ghost** [comment]
This should be merged with the code. I'm also facing this issue. This behavior also occurs when a border is given to  x-rail or y rail just like padding.

**Pull request closed without merging**
