### PR TITLE
fix the error about the touchmove #2

### LINKED ISSUE #843: Fix : Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
Hello, I encounter an issue with the plugin at this script location :

```
...

var timeGap = currentTime - startTime;
      if (timeGap > 0) {
        speed.x = differenceX / timeGap;
        speed.y = differenceY / timeGap;
        startTime = currentTime;
      }

      if (shouldPrevent(differenceX, differenceY)) {
        e.preventDefault(); // Here
      }
```

To prevent the warning a solution is given [here](https://stackoverflow.com/questions/26478267/touch-move-getting-stuck-ignored-attempt-to-cancel-a-touchmove#answer-53315365).

Thank you!

### PR DESCRIPTION
**Pull request by morr**
It is basically #810 rebased to the current master branch.

Closed #843 is also related

It fixes error in google chrome
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

### CODE REVIEW

**Comment by Peter-Zakharevich** [comment]
Hi, @mattonit! Could you please review this PR

**Comment by Peter-Zakharevich** [comment]
Hi, @pglejzer ! Could you please review this PR

**Comment by Peter-Zakharevich** [comment]
Hi everyone @mattonit @pglejzer is this PR have any chances to be reviewed and include to the next release?

**Comment by kamaladenalhomsi** [comment]
+1

**Comment by vas-dev002** [comment]
+1 We also need this fix for our application

**Comment by fruitbat2000** [comment]
+1

**Comment by morr** [comment]
Well until this is patch is not merged, @Peter-Zakharevich, @kamaladenalhomsi, @vas-dev002, @fruitbat2000 I suggest you to temporarily switch to `morr/perfect-scrollbar#master` or `morr/perfect-scrollbar#1.5.3` - it contains this fix and all code from `mdbootstrap/perfect-scrollbar#master`

**Pull request closed without merging**
