### PR TITLE
RTL scroll fix

### PR DESCRIPTION
**Pull request by arl1nd**
Fixed the issue with RTL where scrollbar continuously extends.

### CODE REVIEW

**Comment by hatashiro** [comment]
Please check formatting.

**Comment by arl1nd** [comment]
Hi Hyunje,

Since this is my first commit to Github I am not sure how this works. Otherwise you can simply add the fix from your account (if thats the correct way)

**Comment by hatashiro** [comment]
Hi, please run ‘npm run format’ in your env, and it will automatically format the source files. Please commit and push the diff.

**Comment by hatashiro** [comment]
Moved to #722.

**Pull request closed without merging**
