### PR TITLE
Fix touch propagation

### PR DESCRIPTION
**Pull request by zalesky**
- [x] Read [CONTRIBUTING.md](../CONTRIBUTING.md)
- [x] Run `npm test` to make sure it formats and build successfully
- [ ] Provide the scenario this PR will address(some JSFiddles will be perfect)
- [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Refer to concerning issues if exist

The main propblem is that scroll area in scroll area doesn't work properly, this PR will fix it.
The reason is why I removed preventing for chrome page update is - beter to use ```overscroll-behavior: none``` in such cases.

### CODE REVIEW

**Review by ViniciusLavrador — APPROVED** [review]
Seems to fiz issue #947

**Comment by ahorek** [comment]
@mattonit may I ask for a review? I can confirm it works fine.

**Comment by zalesky** [comment]
I wonder if that was fixed  in any other way 🙂

**Comment by filipkappa** [comment]
Hi, we've moved this to our taskboard and will be working on it soon ;)

**Pull request closed without merging**
