### PR TITLE
No longer require to manually add overflow:hidden, plugin does this. [#285]

### PR DESCRIPTION
**Pull request by DanielApt**
See #285

### CODE REVIEW

**Comment by hatashiro** [comment]
Would you please update `README.md` as well? I think we can just move `the container must have an 'overflow:hidden' css style.` line to the next category, `included in the basic CSS`.

**Comment by DanielApt** [comment]
Agreed, will change both. Bear with me…

**Comment by DanielApt** [comment]
I've just finished working on your requests. Hope it's ready for merging.

**Comment by hatashiro** [comment]
Great work. Thanks!

**Pull request merged**
