### PR TITLE
Fix typo - border-transparen -> border-transparent

### PR DESCRIPTION
**Pull request by whamtet**
Looks like a minor typo!

### CODE REVIEW

**Comment by smolenski-mikolaj** [comment]
@cla-bot check

**Comment by whamtet** [comment]
@smolenski-mikolaj I signed the cla, can you rerun the bot please?

**Comment by juujisai** [comment]
@cla-bot check

**Comment by juujisai** [comment]
Thank you for your Pull Request. I have merged this to our v1.0.0-beta3 dev branch and the changes will be available next release.

**Pull request merged**
