### PR TITLE
Perfect Scrollbar Issues 89

### PR DESCRIPTION
**Pull request by WebStew**
Hey,

This resolved the problem for me outlined in issue 89. However I have not had time to properly test this patch nor enough time here to be confident it is the best approach. 

Regards
Stu

### CODE REVIEW

**Comment by hatashiro** [comment]
Hello,

Each commit's diff is kinda wrong cause of tabsize problem. If the second commit is for fixing it, I think it should be amended to the first one. But nevermind, I can amend it when merging them.

But now I'm not sure it's okay to use `$.now()` to identify the plugin object. It'll be very nice if there's any api that returns the unique identifier for a specific jQuery object, but I don't have any idea yet.

Anyway, the patch looks very good. I'll merge it after I have a little more time to think about the patch.

Thanks!

**Comment by WebStew** [comment]
Hey,

Yeah my apologies on the bad commit. My IDE screwed your formatting. I know what you mean about the UID approach and I'm not sure it is the best way to resolve the issue however I had a deadline here and had to patch it as quickly as possible. I will endeavour to come back to this and see if I can find a better approach. If I do, I'll update the src and recommit on this fork.

Regards
Stu

**Comment by hatashiro** [comment]
Hello,

The issue is resolved with the patch 771ed0c32f0d30b228f4aad4f68432ce2ac1ecc4.
It implements the function to return a unique event class name.

But your report and patch really helps me to do the job. Thank you very much.

**Comment by WebStew** [comment]
Hey,

No problem at all. Glad it helped :)

**Pull request closed without merging**
