### PR TITLE
Add parameter to give option of turning off scrolling with wheel. 

### PR DESCRIPTION
**Pull request by c4l3b**
Pamameter: useWheelScroll -- default: true

### CODE REVIEW

**Comment by DanielApt** [comment]
Thanks for the pull request @cmbertsch01 

Just so I understand, in what scenario would this behaviour be desirable?

**Comment by c4l3b** [comment]
You're welcome and thanks for the consideration!
I love the perfect scrollbar project, and used it in a horizontal product
slider. It's very similar to the sliders on Amazon's homepage. There is an
issue, specifically when using a touch pad, when scrolling the whole page
and the cursor is over the perfect scrollbar container. It will catch any
horizontal scroll and stop scrolling the page. I wish I could give you an
example, but it would require you to be a registered user. Amazon's slider
is not bound to the wheel and I'm guessing it's for this reason.

Thanks!

Caleb

**Comment by hatashiro** [comment]
I would like to implement this feature, but with a different form of option parameter. I'll do the work in short, but anyway will merge the patch for the time being.

Thanks!

**Comment by hatashiro** [comment]
Oops, I found a little problem in this PR that it should be done in `initialize.js`, instead of the handler itself. I'll revert the patch. Sry, and thanks again!

**Comment by hatashiro** [comment]
It's implemented with bd7134f33dbba3073d3f7f0d4204de8edf85ae72

**Pull request merged**
