### PR TITLE
Ripple - fix issue with class customization

### LINKED ISSUE #1798: Ripple - fix class customization issues

### PR DESCRIPTION
**Pull request by juujisai**

### CODE REVIEW

**Comment by juujisai** [comment]
@cla-bot check

**Comment by juujisai** [comment]
@cla-bot check

**Comment by juujisai** [comment]
@cla-bot check

**Comment by smolenski-mikolaj** [comment]
@cla-bot check

**Comment by smolenski-mikolaj** [comment]
@cla-bot check

**Comment by juujisai** [comment]
@cla-bot check

**Comment by smolenski-mikolaj** [comment]
@cla-bot check

**Comment by smolenski-mikolaj** [comment]
@cla-bot check

**Comment by juujisai** [comment]
@cla-bot check

**Comment by juujisai** [comment]
@cla-bot check

**Comment by juujisai** [comment]
@cla-bot check

**Comment by juujisai** [comment]
@cla-bot check

**Pull request merged**
