### PR TITLE
Added updateReach and emitEvents parameters for the update method

### PR DESCRIPTION
**Pull request by sconix**
Regarding the issue #695, the added reach parameter helps a bit, but still forces having duplicating code for checking the reach state after programmatic scroll specially since the updateScroll call in update was removed.

My suggestion is in this PR, very simple changes to allow updating reach / scroll with update call and also to be able to send the events on if wanted. With these changes I would not need to replicate any of the perfect-scrollbar code in the ngx-perfect-scrollbar angular wrapper library.

I would really appreciate if you can consider merging this or discussing about better solution.

### CODE REVIEW

**Comment by hatashiro** [comment]
I think we actually we do not need the parameters, as using them by default seems like making sense.

I think we can separate the task to make it default, so I'll merge this when it passes the CI.

**Comment by sconix** [comment]
I can't say for sure which makes more sense having them as default or not, but imho having an update call with more finer control about what to update is not a bad thing. Anyway I am happy with either way.

**Comment by hatashiro** [comment]
Please exclude `dist` from updates. They are updated only when a new version is released.

**Comment by sconix** [comment]
Ah sorry, forgot that I run build so should not have used -a.

**Comment by hatashiro** [comment]
Merged. Thanks! I'll write a follow-up patch in a while.

**Comment by hatashiro** [comment]
Uploaded a follow up. Basically the patch makes it default. As you mentioned, there are many cases where contents are dynamically changed and reach states are updated according to the change. I guess it's completely natural to update `reach` and fire the reach events on `update()` call.

Thanks again! It will be released in the next version. I'm not sure when, but it'll be soon hopefully :)

**Comment by sconix** [comment]
At least there hasn't been problems with 0.8.x which worked like that. If the need arises then its very easy to add the emitEvents parameter back, at least updating the reach values always should not be an issue to anyone. 

If you can release in few days it would be nice so I can get the next release out for the ngx-perfect-scrollbar which latest release I already had to pullback once since did not check carefully if the 0.8->1.x change broke anything :)

**Comment by sconix** [comment]
Any change to ger new release out :) Angular 5 was just released so would like to release new major version of my wrapper and would love to have it use 1.x, but for that I need release with these event changes.

**Comment by hatashiro** [comment]
Released into v1.2.0

**Pull request merged**
