### PR TITLE
Add support of iframe for keyboard event

### PR DESCRIPTION
**Pull request by antoinegomez**
Really simple piece of code to add support of iframe in keyboard event activeElement test.

### CODE REVIEW

**Comment by DanielApt** [comment]
Thanks @antoinegomez!

Just double checking, `perfect-scrollbar` already works on `iframe`

Is the scenario you're trying to address scrolling a `perfect-scrollbar` _inside_ an `iframe`?

**Comment by antoinegomez** [comment]
Yes the ps is inside an iframe, it's works well appart from the dection of editable elements

**Comment by DanielApt** [comment]
Sorry, could you expand on that?

On Sunday, 31 January 2016, Antoine Gomez notifications@github.com wrote:

> Yes the ps is inside an iframe, it's works well appart from the dection of
> editable elements
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/noraesae/perfect-scrollbar/pull/447#issuecomment-177660823
> .

## 

This e-mail and any attachments to it are confidential and may also be
legally privileged. If you are not the addressee or have otherwise received
it in error, you are on notice of its status. Please telephone or email the
sender and delete this e-mail. If you are not the addressee, please do not
copy this e-mail or attachments or use it for any purposes, or disclose the
contents to any other person.

For further information about Knowsis Limited, please see our website at
http://www.knows.is

**Comment by antoinegomez** [comment]
Of course, I use ps inside an iframe and I encountered a bug with a textarea input: when using space key ps is scrolling the content. I looked on the code and found out this place where it detects if the active element is editable or not. The element was not retrieved from the iframe. I added a check to know if the element is an iframe and support that use case. Shouldn't break anything I guess.

**Comment by DanielApt** [comment]
Sorry for the late reply. I must have missed your response. I'll review your pull-request this weekend. Hopefully we can get this merged soon!

**Comment by DanielApt** [comment]
@antoinegomez Apologies, I've had to do some unexpected work this weekend, and won't be able to review your work just yet. Don't worry, I hope to review it soon.

**Comment by DanielApt** [comment]
Great work! I've just finished testing it, and can confirm it fixes the bug. Thanks for your great work and feel free to tackle any of our other [issues](https://github.com/noraesae/perfect-scrollbar/issues)!

**Pull request merged**
