### PR TITLE
Use vertical scroll for horizontal scrollbar if only horizontal scrollbar is present

### PR DESCRIPTION
**Pull request by jtmalinowski**
It might be slightly more convenient to be able to use vertical scroll wheel for horizontal scrollbar if vertical scrollbar is not present, what do you think?

### CODE REVIEW

**Comment by hatashiro** [comment]
Sounds good! But how about making it optional? Conventionally, the features that is not supported by native scrollbar have been adopted with optional parameters.

You can find the example of the optional feature here: #48.

And the min files should not be included. Please remove them from the diff.

Thank you!

**Comment by jtmalinowski** [comment]
Done, updated docs too. Let me know if it's alright.

**Comment by hatashiro** [comment]
Seems good!

And for the last one, I'm very sorry but can you add an example code in 'examples' directory?
There're example codes for optional parameters to help people know how to use the option.

Thank you.

**Comment by hatashiro** [comment]
Never mind. I've added an example while refactoring the code :D

Thank you very much!

**Comment by jtmalinowski** [comment]
Was going to take a stab at it today... Anyway, awesome!

**Pull request merged**
