### PR TITLE
Added alwaysVisibleX and alwaysVisibleY options

### PR DESCRIPTION
**Pull request by asiviero**
Hello @noraesae, we've been using perfect scrollbar in our website but we needed it to be always visible in some blocks, so I added a couple of options to make it possible.

Hope you like it :D

### CODE REVIEW

**Comment by hatashiro** [comment]
You can do this by changing the css without any script change.
It's a bit changed now but you can refer to the issue #27 

Thanks.

**Comment by asiviero** [comment]
Wouldn't it be simpler if everything could be set in a single place for the scrollbar?

**Comment by hatashiro** [comment]
I'm very sorry but I don't want to have something about CSS style in the script. I think that they should be separated however the implementation is very simple. It's not about functionality, but about design pattern.

I'm sorry again and thank you very much for your interest in my plugin.

**Comment by asiviero** [comment]
No problem at all, the plugin is really great :D

**Comment by hatashiro** [comment]
Thank you for your kindness :)

**Comment by juanghurtado** [comment]
Is this still the way to do it? My `ps-scrollbar-x-rail` has a `display: none` (and `opacity: 1`), and changing it to `block` on my CSS doesn't seems to work because the "drag bar" is not shown. The maths for the width of the "drag bar" seems to begin after first scroll on the scroller, so it can't be visible on page load.

Am I doing something wrong?

**Comment by mantia11** [comment]
@juanghurtado the same

**Comment by hatashiro** [comment]
Hi,

Sorry for the incorrect information. Actually it's nothing to do with the `display` css. Instead, please change every reference of `opacity: 0` to `opacity: 0.6`.

Also, in the development version, The stylesheet source is changed to use scss. There's an instruction about the problem for the new source in [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ).

Thanks.

**Comment by mantia11** [comment]
Thanks, now it works okay!

**Comment by kpturner** [comment]
What if you want the scrollbar to be permanently visible in some containers and not in others.  Changing the CSS does not really lend itself to that sort of requirement does it?   It would be easier, and more intuitive, for this to be an option on the plug-in wouldn't it?

**Comment by hatashiro** [comment]
@kpturner If two scrollbars should be shown differently, I think it'd be better to have different CSS styles for each container. I'll update the FAQ and add information to achieve this more easily.

Thanks!

**Comment by hatashiro** [comment]
@kpturner I've just updated [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ) and add some information. I also added an example code, `always-visible.html`, in a `examples` directory to help users understand how it works. I hope it could help you.

Thanks.

**Pull request closed without merging**
