### PR TITLE
Add RTL support for webkit

### PR DESCRIPTION
**Pull request by jotele**
Hi @noraesae,
I've added RTL support for webkit browsers, with minimum code changes.
Supporting other browsers requires much more changes, which requires much more work!
For now, consider merging this tiny feature. It makes perfect-scrollbar even more perfect, but only for webkit users, so far!

### CODE REVIEW

**Comment by hatashiro** [comment]
Thank you very much for your work!

But I'm very sorry but you should lint your code before I merge them. About linting the code, please refer to [Contributing](https://github.com/noraesae/perfect-scrollbar/wiki/Contributing) document. And I think `isRtl` is more suitable for the variable name than just `rtl`.

I merged the README typo fix and you don't need to include it in pull request.

Thank you.

**Comment by jotele** [comment]
Code is clean now, sorry about that.
However, I couldn't find a way to exclude commits from my pull request..
I could only find an edit button for the title of the pull request!
Am I missing something?

**Comment by hatashiro** [comment]
You can squash commits with `git rebase -i` command or `git commit --amend`.

Btw, I just checked your patches and I think the patches make the y-axis scrollbar attached to left. We should be careful about this action, because I already have a plan to implement a left-aligned y-axis scrollbar or top-aligned x-axis scrollbar. This feature has been asked several times.

It may take for a while to merge this, but it'll be merged asap.

Thanks.

**Comment by jotele** [comment]
I hoped to have such an option instead of aligning the scrollbar manually. Great news you have such plan.

**Comment by hatashiro** [comment]
Merged with 14d253abd1003f7bf4b29480d8a545ce3501c048. Thanks!

**Pull request closed without merging**
