### PR TITLE
Unable to scroll by touching (Chrome)

### PR DESCRIPTION
**Pull request by zalesky**
On my laptop with touch screen PerfectScrollbar didn't work by touching in Chrome.
This PR will fix it. 
JFYI http://www.stucox.com/blog/you-cant-detect-a-touchscreen/

### CODE REVIEW

**Comment by kevintruby** [comment]
I hope this merges in soon. I was having an issue with PerfectScrollbar on a Vue application running on a touch screen that seems to be using some sort of IR frame to detect touch events.

Temporarily copied the **dist** esm build in a local **libs** directory and altered my es6 import statement, implementing the code change from the final commit, and everything is working perfectly! Would love to pull in a newer version with this, and cut the local dependency.

Just my two cents, and thank you so much for sharing this; was driving me crazy!

**Comment by mattonit** [comment]
@pglejzer, is this related to your issue #867?

**Comment by pglejzer** [comment]
> @pglejzer, is this related to your issue #867?

I think so.

**Comment by pc-vmora** [comment]
@mattonit [#867](https://github.com/mdbootstrap/perfect-scrollbar/issues/867) this PR is merged but it is not released. When can we expect it to be released?

**Pull request merged**
