### PR TITLE
Fix #1949 Done updating default text color to #4f4f4f through classes

### LINKED ISSUE #1949: Update default text color to #4f4f4f

### PR DESCRIPTION
**Pull request by shubhalgupta**

### CODE REVIEW

**Comment by shubhalgupta** [comment]
@juujisai please review the same!

**Comment by shubhalgupta** [comment]
@juujisai kindly merge this!

**Comment by juujisai** [comment]
@shubhalgupta As I wrote in previous PR's, this is a major change. It won't be merged soon

**Comment by juujisai** [comment]
Hi! Thank you for helping and submitting this Pull Request. I've merged this to the `v2.0.0` branch.

**Pull request merged**
